### ISSUE TITLE
List back-ends in capabilties doc

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-aggregator#22]
see https://github.com/Open-EO/openeo-api/pull/419 for first iteration of how to list them

**Comment by jdries** [comment]
Looking at the federation extension, this seems to be about adding a title and description to what we already have:

https://github.com/Open-EO/openeo-api/tree/master/extensions/federation#example

```
{
  "api_version": "1.2.0",
  "federation": {
    "vito": {
      "title": "VITO",
      "url": "https://openeo.vito.be"
    },
    "eodc": {
      "title": "EODC",
      "url": "https://openeo.eodc.eu"
    },
    "wwu": {
      "title": "WWU Münster",
      "url": "https://openeo.wwu.de",
      "status": "offline",
      "description": "Experimental integration of the WWU HPC",
      "experimental": true
    }
  },
  ...
}
```

**Comment by soxofaan** [comment]
If I understand correctly, title and description are actually optional, so what we currently have is already valid

**Comment by soxofaan** [comment]
added title/description with 40e7dd9

probably more interesting are these:
```
          status:
            type: string
            enum:
              - online
              - offline
            description: Current status of the back-ends.
            default: online
          last_status_check:
            type: string
            format: date-time
            description: The time at which the status of the back-end was checked last.
          last_successful_check:
            type: string
            format: date-time
            description: >-
              If the `status` is `offline`: The time at which the back-end was checked and available the last time.
              Otherwise, this is equal to the property `last_status_check`.
```
